name: Artifact Links

on:
  issue_comment:
    types: [created, edited]

jobs:
  pre_check:
    name: Pre-Check
    runs-on: ubuntu-latest
    steps:
      - name: Check if valid PR
        env:
          GH_GH: ${{ toJson(github) }}
          GH_TYPE: ${{ toJson(github.event.issue.pull_request) }}
        run: |
          echo "Event Name  :  $GITHUB_EVENT_NAME"
          echo "Issue / PR #:  ${{ github.event.issue.number }}"
          echo "Type        :  $GH_TYPE"
          echo "Repository  :  ${{ github.repository }}"
          echo "API URL     :  ${{ github.event.repository.url }}"
          echo "Full Object:"
          echo "$GH_GH"
          echo "https://api.github.com/.../artifacts"
